#!/usr/bin/env sh
# Re-vendor clay.h from upstream nicbarker/clay, record provenance in
# CLAY_VERSION, and regenerate the golden corpus. This is the single command to
# run when the Clay repo changes. See UPSTREAM.md for the full workflow.
#
# Usage:
#   ./update-clay.sh <ref>                     # fetch from GitHub at a tag/branch/full-SHA
#   ./update-clay.sh v0.15
#   CLAY_SRC=/path/to/clay ./update-clay.sh    # copy from a local clay checkout (offline)
#
# After it finishes:
#   git diff testdata/   # exactly which scenes upstream changed
#   go test ./...        # does the Go port still reproduce the new goldens?
set -eu

REPO_URL="https://github.com/nicbarker/clay"
HERE="$(cd "$(dirname "$0")" && pwd)"
DEST="$HERE/clay.h"
VERSION_FILE="$HERE/CLAY_VERSION"

# Stage the new header in a temp file and only move it into place once it has
# been validated, so a failed fetch/copy can never clobber the good clay.h.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

if [ -n "${CLAY_SRC:-}" ]; then
    # --- Local checkout mode: exact provenance straight from git, no network.
    #     CLAY_SRC is relative to the oracle/ dir (or absolute). ---
    [ -f "$CLAY_SRC/clay.h" ] || { echo "error: CLAY_SRC=$CLAY_SRC has no clay.h" >&2; exit 1; }
    cp "$CLAY_SRC/clay.h" "$tmp"
    if git -C "$CLAY_SRC" rev-parse --git-dir >/dev/null 2>&1; then
        sha="$(git -C "$CLAY_SRC" rev-parse HEAD)"
        ref="$(git -C "$CLAY_SRC" describe --tags --always 2>/dev/null || echo '(no tag)')"
        cdate="$(git -C "$CLAY_SRC" log -1 --format=%cI HEAD)"
    else
        sha="(unknown — CLAY_SRC is not a git repo)"; ref="(unknown)"
        cdate="$(date -u +%Y-%m-%dT%H:%M:%SZ) (copied)"
    fi
else
    # --- Remote mode: resolve ref -> exact commit SHA, then fetch by SHA so the
    #     pin is precise even when <ref> is a moving branch ---
    ref="${1:-}"
    [ -n "$ref" ] || { echo "usage: $0 <ref>   (or: CLAY_SRC=/path/to/clay $0)" >&2; exit 2; }
    command -v git  >/dev/null 2>&1 || { echo "error: git is required for remote mode"  >&2; exit 1; }
    command -v curl >/dev/null 2>&1 || { echo "error: curl is required for remote mode" >&2; exit 1; }

    refs="$(git ls-remote "$REPO_URL" "$ref" "$ref^{}" 2>/dev/null || true)"
    # Prefer the peeled (^{}) line: for an annotated tag that is the commit SHA.
    sha="$(printf '%s\n' "$refs" | awk '/\^\{\}$/ {print $1; exit}')"
    [ -n "$sha" ] || sha="$(printf '%s\n' "$refs" | awk 'NF {print $1; exit}')"
    [ -n "$sha" ] || sha="$ref"   # no match -> assume caller passed a raw full SHA
    case "$sha" in
        *[!0-9a-f]* | "") echo "error: could not resolve '$ref' to a commit SHA (use a tag, branch, or full 40-char SHA)" >&2; exit 1 ;;
    esac
    echo "resolved $ref -> $sha"
    curl -fsSL "https://raw.githubusercontent.com/nicbarker/clay/$sha/clay.h" -o "$tmp"
    cdate="$(date -u +%Y-%m-%dT%H:%M:%SZ) (fetched)"
fi

# Sanity-check the staged header before it replaces the committed one.
[ -s "$tmp" ] || { echo "error: vendored clay.h is empty — refusing" >&2; exit 1; }
grep -q "zlib" "$tmp" || { echo "error: vendored clay.h has no zlib license notice — refusing" >&2; exit 1; }
mv "$tmp" "$DEST"

cat > "$VERSION_FILE" <<EOF
# Provenance of oracle/clay.h — DO NOT EDIT BY HAND.
# Regenerated by oracle/update-clay.sh. See oracle/UPSTREAM.md for the workflow.
upstream:    $REPO_URL
ref:         $ref
commit:      $sha
commit-date: $cdate
license:     zlib/libpng (notice retained in clay.h and ../LICENSE.md)
EOF

echo "vendored clay.h @ $sha"
echo "regenerating goldens..."
make -C "$HERE" regenerate

cat <<'EOF'

Done. From the repo root, review what changed, then update the Go port if needed:
  git diff testdata/    # exactly which scenes upstream changed
  go test ./...         # does the Go port still match the new goldens?
EOF
